# Generated by Django 2.2 on 2019-07-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
