# Generated by Django 2.2 on 2019-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_auto_20190722_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
