# Generated by Django 2.2 on 2019-07-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_reminder_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
